/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import type { KyberStorage } from './KyberStorage';

export class KyberStorageFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): KyberStorage {
    return new Contract(address, _abi, signerOrProvider) as KyberStorage;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'kyberProxy',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'maxApprovedProxies',
        type: 'uint256',
      },
    ],
    name: 'addKyberProxy',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
    ],
    name: 'getEntitledRebateData',
    outputs: [
      {
        internalType: 'bool[]',
        name: 'entitledRebateArr',
        type: 'bool[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
    ],
    name: 'getFeeAccountedData',
    outputs: [
      {
        internalType: 'bool[]',
        name: 'feeAccountedArr',
        type: 'bool[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getKyberProxies',
    outputs: [
      {
        internalType: 'contract IKyberNetworkProxy[]',
        name: '',
        type: 'address[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
    ],
    name: 'getRebateWalletsFromIds',
    outputs: [
      {
        internalType: 'address[]',
        name: 'rebateWallets',
        type: 'address[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'reserveId',
        type: 'bytes32',
      },
    ],
    name: 'getReserveAddressesByReserveId',
    outputs: [
      {
        internalType: 'address[]',
        name: 'reserveAddresses',
        type: 'address[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
    ],
    name: 'getReserveAddressesFromIds',
    outputs: [
      {
        internalType: 'address[]',
        name: 'reserveAddresses',
        type: 'address[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'token',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'startIndex',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'endIndex',
        type: 'uint256',
      },
    ],
    name: 'getReserveAddressesPerTokenSrc',
    outputs: [
      {
        internalType: 'address[]',
        name: 'reserveAddresses',
        type: 'address[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'reserve',
        type: 'address',
      },
    ],
    name: 'getReserveDetailsByAddress',
    outputs: [
      {
        internalType: 'bytes32',
        name: 'reserveId',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'rebateWallet',
        type: 'address',
      },
      {
        internalType: 'enum IKyberStorage.ReserveType',
        name: 'resType',
        type: 'uint8',
      },
      {
        internalType: 'bool',
        name: 'isFeeAccountedFlag',
        type: 'bool',
      },
      {
        internalType: 'bool',
        name: 'isEntitledRebateFlag',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'reserveId',
        type: 'bytes32',
      },
    ],
    name: 'getReserveDetailsById',
    outputs: [
      {
        internalType: 'address',
        name: 'reserveAddress',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'rebateWallet',
        type: 'address',
      },
      {
        internalType: 'enum IKyberStorage.ReserveType',
        name: 'resType',
        type: 'uint8',
      },
      {
        internalType: 'bool',
        name: 'isFeeAccountedFlag',
        type: 'bool',
      },
      {
        internalType: 'bool',
        name: 'isEntitledRebateFlag',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'reserve',
        type: 'address',
      },
    ],
    name: 'getReserveId',
    outputs: [
      {
        internalType: 'bytes32',
        name: 'reserveId',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'reserveAddresses',
        type: 'address[]',
      },
    ],
    name: 'getReserveIdsFromAddresses',
    outputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'token',
        type: 'address',
      },
    ],
    name: 'getReserveIdsPerTokenDest',
    outputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'token',
        type: 'address',
      },
    ],
    name: 'getReserveIdsPerTokenSrc',
    outputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'reserveIds',
        type: 'bytes32[]',
      },
      {
        internalType: 'contract IERC20',
        name: 'src',
        type: 'address',
      },
      {
        internalType: 'contract IERC20',
        name: 'dest',
        type: 'address',
      },
    ],
    name: 'getReservesData',
    outputs: [
      {
        internalType: 'bool',
        name: 'areAllReservesListed',
        type: 'bool',
      },
      {
        internalType: 'bool[]',
        name: 'feeAccountedArr',
        type: 'bool[]',
      },
      {
        internalType: 'bool[]',
        name: 'entitledRebateArr',
        type: 'bool[]',
      },
      {
        internalType: 'contract IKyberReserve[]',
        name: 'reserveAddresses',
        type: 'address[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isKyberProxyAdded',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'kyberProxy',
        type: 'address',
      },
    ],
    name: 'removeKyberProxy',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_kyberFeeHandler',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_kyberMatchingEngine',
        type: 'address',
      },
    ],
    name: 'setContracts',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_kyberDao',
        type: 'address',
      },
    ],
    name: 'setKyberDaoContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
