/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import type { PriceFeed } from './PriceFeed';

export class PriceFeedFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): PriceFeed {
    return new Contract(address, _abi, signerOrProvider) as PriceFeed;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: 'address',
        name: 'fromToken',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'toToken',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'srcAmount',
        type: 'uint256',
      },
    ],
    name: 'getBestPriceSimple',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'address',
        name: 'fromToken',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'toToken',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'srcAmount',
        type: 'uint256',
      },
    ],
    name: 'getBestPrice',
    outputs: [
      {
        components: [
          {
            internalType: 'uint256',
            name: 'rate',
            type: 'uint256',
          },
          {
            components: [
              {
                internalType: 'uint256',
                name: 'Uniswap',
                type: 'uint256',
              },
              {
                internalType: 'uint256',
                name: 'Bancor',
                type: 'uint256',
              },
              {
                internalType: 'uint256',
                name: 'Kyber',
                type: 'uint256',
              },
              {
                internalType: 'uint256',
                name: 'Oasis',
                type: 'uint256',
              },
            ],
            internalType: 'struct Types.RateDistribution',
            name: 'distribution',
            type: 'tuple',
          },
        ],
        internalType: 'struct Types.OptimalRate',
        name: 'optimalRate',
        type: 'tuple',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
];
